<a href="https://colab.research.google.com/github/VejeyPradeep/CE888/blob/master/lab1/DS%26DM_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[1] Creating and printing attributes of a 4x2 numpy array

In [0]:
import numpy as np
a = np.array([[0,1],[2,3],[4,5],[6,7]])
print(a.ndim)
print(a.shape)
print(a)

2
(4, 2)
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


[2] Create an array of dimension (1,10) and sort it in ascending and descending order

In [0]:
b = np.array([1,5,2,4,3,6,7,8,9,0])
print('ascending order--->',np.sort(b))
print('descending order--->', np.sort(b)[::-1])

ascending order---> [0 1 2 3 4 5 6 7 8 9]
descending order---> [9 8 7 6 5 4 3 2 1 0]


[3] Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]

In [0]:
c = np.array([1,2,3,4,5,6,7,8,9])
c = np.split(c,3)
print(c)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


[4] Stack two arrays of any size horizontally and vertically

In [0]:
d = np.array([1,2,3])
e = np.array([7,8,9])
print('vertical stack--->',np.stack((d,e)))
print('horizontal stack--->',np.stack((d,e),axis = -1))

vertical stack---> [[1 2 3]
 [7 8 9]]
horizontal stack---> [[1 7]
 [2 8]
 [3 9]]


[5] Create two array of same size and find commom elements

In [0]:
g= np.array([1,2,8,3,4])
h= np.array([5,4,6,7,8])
np.intersect1d(g,h)



array([4, 8])

[6] Create a 2D array of 5 by 5 and find the min and max values from each row and each column

In [0]:
j = np.arange(25).reshape(5,5)
print(j)
print('max in column--->',j.max(axis=0))
print('min in column--->',j.min(axis=0))

for i in j:
  print('max in row--->',np.amax(i))
  print('min in row--->',np.amin(i))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
max in column---> [20 21 22 23 24]
min in column---> [0 1 2 3 4]
max in row---> 4
min in row---> 0
max in row---> 9
min in row---> 5
max in row---> 14
min in row---> 10
max in row---> 19
min in row---> 15
max in row---> 24
min in row---> 20


[7] Create an array of size 100 and  compute the mean, median, standard deviation.

In [0]:
array = np.random.randint(200, size = 100)
print(array)
print('mean--->', np.mean(array))
print('median-->',np.median(array))
print('std deviation-->', np.std(array))

[ 61 103  65 118  46 181 183 160  54  43  54  93  18 122 148 184   6  99
  35  31 156 148  82  37  44  63 128 126 175 137  35  64  41  39  73 187
  49  97 143  26  20 134  63  47  72 147  77  29  64 121 117 160  12 199
  12 112  65  37 126 101  44  55 184  97  99 114  65  94  45 159  12 155
 132  34  83  57  74 177 179 139  44 118 150  81  44 183 123  46  91  95
 113  92 189  23   3 105 130  37 159  29]
mean---> 92.22
median--> 91.5
std deviation--> 52.86181608685044


[8] Normalize a 5x5 random matrix 

In [0]:
arr = np.random.randint(0, 100, (5,5))
print(arr)
from sklearn.preprocessing import normalize
normed_matrix = normalize(arr, axis=1, norm='l2')
print(normed_matrix)

[[58  1 30 72 80]
 [13 81 20 51 25]
 [92 53 80 45 63]
 [49 61 25 13 37]
 [74 25 29 73 88]]
[[0.46070939 0.00794327 0.23829796 0.5719151  0.63546122]
 [0.12774601 0.79595588 0.19653232 0.50115741 0.2456654 ]
 [0.59802071 0.34451193 0.52001801 0.29251013 0.40951418]
 [0.53833154 0.67016783 0.27465895 0.14282265 0.40649524]
 [0.52306291 0.17671044 0.20498411 0.51599449 0.62202075]]


[9] Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?

In [0]:
arry1 = np.random.randint(99, size=(4,4,3))
arry2 = np.random.randint(99 , size = (4,4))
print(arry1 * arry2[:,:,None])

[[[ 368 5704  460]
  [ 132  594 1254]
  [ 405  324 7128]
  [1950 3276 2847]]

 [[ 776  970  291]
  [ 448  408  752]
  [ 679  581  476]
  [2697   31 2635]]

 [[1305 2639 1798]
  [2142 2772 3969]
  [ 340 2754 1428]
  [ 220  490  470]]

 [[ 270 2520 3240]
  [2812 6808 2368]
  [ 108 2160 1917]
  [1554 3552 3626]]]
